getd = @(p)path(p,path); % scilab users must *not* execute this
getd('toolbox_signal/');
getd('toolbox_general/');
p = 10;
[h,g] = compute_wavelet_filter('Daubechies',p);
disp(['h filter = [' num2str(h) ']']);
disp(['g filter = [' num2str(g) ']']);
%N = 256;
%f = rand(N,1);
f = xlsread('2.xlsx');
a = subsampling( cconv(f,h) );
d = subsampling( cconv(f,g) );
f1 =  cconv(upsampling(a),reverse(h)) + cconv(upsampling(d),reverse(g));
%disp(strcat((['Error |f-f1|/|f| = ' num2str(norm(f-f1)/norm(f))])));
name = 'piece-regular';
N = 512;
f = rescale( load_signal(name, N) );
clf;
plot(f);
axis('tight');
fw = f;
j = log2(N)-1;
a1 = fw(1:2^(j+1));
a = subsampling(cconv(a1,h));
d = subsampling(cconv(a1,g));
fw(1:2^(j+1)) = cat(1, a, d );
clf;
subplot(2,1,1);
plot(f); axis('tight'); title('Signal');
subplot(2,1,2);
plot(fw); axis('tight'); title('Transformed');
s = 400; t = 40;
clf;
subplot(2,1,1);
plot(f,'.-'); axis([s-t s+t 0 1]); title('Signal (zoom)');
subplot(2,1,2);
plot(a,'.-'); axis([(s-t)/2 (s+t)/2 min(a) max(a)]); title('Averages (zoom)');